# Generated by Django 5.0 on 2024-12-08 07:20

import ckeditor.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
